import pandas as pd

varName = [
    'avgDur',
    'avgTimeOnSite',
    'avgView',
    'bounceRate',
    'ezmail',
    'direct',
    'domestic',
    'fb',
    'foreign',
    'line',
    'party',
    'oldSite',
    'organic',
    'pagePS',
    'pageTitle',
    'pageView',
    'paidsearch',
    'promotion',
    'referral',
    'sessions',
    'social',
    'tps',
    'users',
    'value',
    'registPhone',
    'registMail',
]
print({a: [] for a in varName})
